import type { Metadata } from "next";

import Providers from '@/lib/Providers'
import "./globals.css";
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import { Poppins } from "next/font/google";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400", "500", "600"], // Customize weights as needed
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
    <html lang="en">
    <body className={`${poppins.variable} ${poppins.variable} antialiased`}>{children}</body>
    </html>
</Providers>
  );
}
